config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

  resources :orders, except: [:index]
  # root to: 'orders#new'

  resources :flavors
  # root to: 'flavors#new'

  resources :toppings
  # root to: 'toppings#new'

  resources :containments
  # root to: 'containments#new'

  resources :customers
  # root to: 'containments#new'


end

app/models/containment.rb
class Containment < ActiveRecord::Base
  belongs_to :order
  has_one :flavor

  has_many :toppings

  validates :name, presence: true,
            allow_blank: false,
            uniqueness: true

  has_attached_file :avatar_file_name, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :order


end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  belongs_to :containment


  # validates :name, presence: true,
  #           allow_blank: false,
  #           uniqueness: true


end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :containment
  has_one :flavor, :through => :containment

  has_many :toppings
  has_many :toppings, :through => :containment

  has_one :customer
  accepts_nested_attributes_for :customer, :containment, :flavor, :toppings

  # validates
  #           allow_blank: false,
  #           uniqueness: true


end

  # <%= simple_form_for Customer.new do |f| %>
  # <%= f.association :customer %>
  # <%= f.input :name %>
  # <%= f.input :phone %>
  # <%= f.input :email %>
  # <%= f.button :submit %>
  # <% end %>
    # <%= f.label :text %><br>
    # <%= f.text_area :text %>

app/models/topping.rb
class Topping < ActiveRecord::Base
  belongs_to :containment

  validates :name, presence: true,
            allow_blank: false,
            uniqueness: true

  has_attached_file :avatar_file_name, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/containments_controller.rb
class ContainmentsController < ApplicationController
  suckr = ImageSuckr::GoogleSuckr.new


  def index
    @containments = Containment.all
  end

#no view for this
def new
  @containment = Containment.new
end

def create
  @containment = Containment.new(containment_params)

  if @containment.save
    redirect_to @containment
  else
    render 'new'
  end
end

def destroy
  @containments = containments.find(params[:id])
  @containments.destroy

  respond_to do |format|
    format.html { redirect_to(containments_url) }
    format.xml  { head :ok }
  end
end


  private
  def containment_params
    params.require(:containment).permit(:name)
    params.require(:containment).permit(:avatar)

  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new
  end

  def show
  end

  def index
    @customer = Customer.new

  end
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController

  def index
    @flavors = Flavor.all
  end

  def new
    @flavor = Flavor.new
  end

  def create
    @flavor = Flavor.new(flavor_params)
    if @flavor.save
      redirect_to @flavor
    else
      render 'new'
    end
  end

  def destroy
    @flavors = flavors.find(params[:id])
    @flavors.destroy

    respond_to do |format|
      format.html { redirect_to(flavors_url) }
      format.xml  { head :ok }
  end
end
    private
    def flavor_params
      params.require(:flavor).permit(:name, :image_url)
    end


  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
require 'pry'
class OrdersController < ApplicationController
  require 'mandrill'

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @order.build_customer
    # @order.build_flavor
    # @order.build_containment
    # @order.toppings.build
  end


  def show
    @order = Order.find(params[:id])
  end


  def create
    # binding.pry
    @order = Order.new(order_params)
    @customer = Customer.new
    @flavor = Flavor.new

    if @order.save
      # Emailer.order_email(order)
      redirect_to order_path @order
    else
      # binding.pry
      redirect_to :back
    end
  end

  private
  def order_params
    params.require(:order).permit(
      :customer_id,
      # :containtment_id,
      :flavor_id,
      # :topping_id,
      customer_attributes: [ :id, :name, :address, :phone, :email],
      # containments_attributes: [:id, :name],
      flavors_attributes: [:id, :name, :image_url],
      # toppings_attributes: [:id, :name],
      )
  end
end



# Mailer
#     # Create the order from params
#     @customer = customer.new(params[:customer])
#     if @customer.save
#       # Delivers new order email possibly?
#       emailer.order_email(@customer).deliver
#       redirect_to(@customer, :notice => 'New Order')
#     else
#       render :action => 'new'
#     end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  suckr = ImageSuckr::GoogleSuckr.new


  def index
    @toppings = Topping.all
  end

#no view here
def new
  @topping = Topping.new
end

def create
  @topping = Topping.new(topping_params)

  if @topping.save
    redirect_to @topping
  else
    render 'new'
  end
end

def destroy
  @toppings = toppings.find(params[:id])
  @toppings.destroy

  respond_to do |format|
    format.html { redirect_to(toppings_url) }
    format.xml  { head :ok }
  end
end


  private
  def topping_params
    params.require(:topping).permit(:name)
    params.require(:topping).permit(:avatar)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containments_helper.rb
module ContainmentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/containments/index.html.erb
<h2>Here are the containments we have in stock today!</h2>

<table>
  <tr>
    <th>containment</th>
  </tr>

  <% @containments.each do |containment| %>
    <tr>
     <p> <td><%= containment.name %></td>
      <td><%= image_tag containment.image_url %><br><br></td>
      </p>
    </tr>
  <% end %>
</table>

app/views/flavors/index.html.erb
<h2>Here are all of the flavors we have in stock today!</h2>


<h1>Flavors:</h1>
<table>
  <tr>
    <th>Flavor</th>
  </tr>

  <% @flavors.each do |flavor| %>
    <tr>
     <p> <td><%= flavor.name %></td>
      <td><%= image_tag flavor.image_url %><br><br></td>
      </p>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h2>What's for sale:</h2>

<h3><%= link_to 'Available ice cream flavors with accompanying images', flavors_path %></h3>

<h3><%= link_to 'Ice cream toppings with accompanying images', toppings_path %></h3>

<h3><%= link_to 'Ice cream containment options', containments_path %></h3>



<!-- <h2> :  </h2> -->


<h3>PLACE A NEW ORDER</h3>
<h4>Enter ice cream configuration options (flavor, cone, toppings)</h4>
<li><%= link_to 'Place a new order', order_path('new') %></li>



<!-- <h2>.</h2> -->

<!-- <h2>Admin:</h2>
<h3>Claire can manage orders and options.</h3>
<h3>Claire should easily be able to add new toppings, flavors, etc.</h3>
<h3>Claire should also be able to filter orders by customer or by flavor.</h3>
 -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<<<<<<< HEAD


<li><%= link_to 'Order', order_path('new') %></li>
=======
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
>>>>>>> origin/master

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dairy" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dairy" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Place a new Ice Cream order</h1>



<p>
</p>

<%= link_to 'Flavors', controller: 'flavors' %>
<%= link_to 'Toppings', controller: 'toppings' %>
<%= link_to 'Containments', controller: 'containments' %>



<%= form_for @order do |f| %>
Your info:
<ul>
  <%= f.fields_for :customer do |customer| %>
  <li>
    <%= customer.label :name %>
    <%= customer.text_field :name %>

    <%= customer.label :address %>
    <%= customer.text_field :address %>

    <%= customer.label :phone %>
    <%= customer.text_field :phone %>

    <%= customer.label :email %>
    <%= customer.text_field :email %>
  </li>
  <% end %>
</ul>
Flavors:
<ul>
  <%= f.fields_for :flavors do |flavor_form| %>
  <li>
    <%= flavor_form.label :name, "Pick your flavor" %>
    <%= flavor_form.collection_select :order_id, Flavor.all, :id, :name %>
  </li>
  <% end %>
</ul>
<!-- Toppings:
<ul>
  <%= f.fields_for :toppings do |topping_form| %>
  <li>
    <%= topping_form.label :name, "Pick your topping" %>
    <%= topping_form.collection_select :order_id, Topping.all, :id, :name %>
  </li>
  <% end %>
</ul>
Containments:
<ul>
  <%= f.fields_for :containments do |containment_form| %>
  <li>
    <%= containment_form.label :name, "Pick your containment" %>
    <%= containment_form.collection_select :order_id, Containment.all, :id, :name %>
  </li>
  <% end %> -->


</ul>
<%= f.submit %>
<% end %>

app/views/orders/show.html.erb
<p>
  <strong>You just placed an order</strong>
  <strong>Here is what you picked out</strong>
  <!-- Add logic showing order -->

</p>


<%= link_to 'Go home', controller: 'home' %>

app/views/toppings/index.html.erb
<h2>Here are the toppings we have in stock today!</h2>



<h1>Topping:</h1>
<table>
  <tr>
    <th>Topping</th>
  </tr>

  <% @toppings.each do |topping| %>
    <tr>
     <p> <td><%= topping.name %></td>
      <td><%= image_tag topping.image_url %><br><br></td>
      </p>
    </tr>
  <% end %>
</table>